### ISSUE TITLE
Allow name for variable-select

### ISSUE THREAD

**Issue by Mara-Li** [mgmeyers/obsidian-style-settings#11]
It will be cool to add a display name for the `variable-select`, instead of the full content, something like:

```yaml
    - 
        id: content-icon-transform
        title: Files icon translate
        type: variable-select
        default: translate(var(--icon-x), var(--icon-y))
        options-name: 
            - default
            - option1
        options-value: 
            - translate(-3px, 3px)
            -  translate(0px, 3px)
    - 
 ```
