### ISSUE TITLE
When entering the interface, all color previews will change to the last color

### ISSUE THREAD

**Issue by GoblinCwl** [mgmeyers/obsidian-style-settings#122]
For example, I change one of the colors as shown in the figure:
![Snipaste_2023-05-11_20-53-49](https://github.com/mgmeyers/obsidian-style-settings/assets/40445489/26aee4b4-e632-424e-8406-87934e802257)

When I close the interface, reopen it, or every time I open it, all colors will change to the last line in the group they belong to:
![Snipaste_2023-05-11_20-59-36](https://github.com/mgmeyers/obsidian-style-settings/assets/40445489/18d11957-6f90-4b10-ae33-e6a97fd300a8)

```css
/* @settings

name: GoblinCwl@css
id: GoblinCwl@css
settings:
    -   
        id: taskFailBoxColor
        title: 任务失败复选框颜色
        description: 更改任务状态为“/”时复选框的颜色
        type: variable-color
        opacity: false
        format: hex
        default: '#e66a51'
    -   
        id: taskFailTextColor
        title: 任务失败文本颜色
        description: 更改任务状态为“/”时文本的颜色
        type: variable-color
        opacity: false
        format: hex
        default: '#945b5b'
    - 
        id: dayPannel
        title: Day Pannel 日程表
        type: heading
        level: 1
        collapsed: true
    -   
        id: dayPannelTaskColor
        title: 日程表任务颜色
        description: 更改Day Pannel日程表中任务显示的颜色
        type: variable-color
        opacity: false
        format: hex
        default: '#FFFFFF'
    -   
        id: dayPannelHoverBacakGroudColor
        title: 日程表高亮背景色
        description: 更改Day Pannel日程表高亮背景色
        type: variable-color
        opacity: false
        format: hex
        default: 'var(--interactive-accent-hover)'

*/

body {
    --dayPannelTaskColor: #;
    --dayPannelHoverBacakGroudColor: #;
    --taskFailBoxColor: #;
    --taskFailTextColor: #;
}

/*更改Day Pannel日程表中任务显示的颜色*/
.ei_Copy.svelte-e43ld1.svelte-e43ld1 {
    color: var(--dayPannelTaskColor)!important;
}

/**更改Day Pannel日程表hover背景色*/
.event_item.svelte-e43ld1.svelte-e43ld1:hover{
    background-color: var(--dayPannelHoverBacakGroudColor)!important;
}

.anp-custom-checkboxes [data-task="/"] > input[type=checkbox]:checked, .anp-custom-checkboxes [data-task="/"] > p > input[type=checkbox]:checked, .anp-custom-checkboxes [data-task="/"][type=checkbox]:checked {
    --checkbox-color: var(--taskFailBoxColor);
    --checkbox-color-hover: var(--taskFailBoxColor);
    border-color: var(--taskFailBoxColor) !important;
}

ul > li.task-list-item[data-task="/"], ul > li.task-list-item[data-task="/"] {
    text-decoration: var(--checklist-done-decoration);
    color: var(--taskFailTextColor);
}
```
![Snipaste_2023-05-11_20-53-49](https://github.com/mgmeyers/obsidian-style-settings/assets/40445489/6fa43890-ac6d-4f28-99e8-b0dfda48371f)
