### ISSUE TITLE
Horizontal scroll on Code Blocks

### ISSUE THREAD

**Issue by Alexgar24** [mgmeyers/obsidian-style-settings#138]
Hello,

First and foremost, thank you for the plugin!

The setting `Minimal / Code blocks / Scroll long lines` has been a significant enhancement for me, as it's a preferable alternative to wrapping long lines, which hinders readability. However, the appearance of a scrollbar under each long line detracts from the code's readability. Addressing this would benefit many users. A simple Google search for "horizontal scroll in code blocks in Obsidian" will highlight the number of individuals seeking a solution to this problem.

Thanks!

**Comment by kbumsik** [comment]
I would like to have this feature too!

Maybe "Word wrap" would be more precise feature.

I personally add a CSS snippet and enable it in "Appearance" Setting:

```css
/*un-wrap code*/
.HyperMD-codeblock {
    white-space: nowrap;
}

/*scroll codeblock in read mode*/
.markdown-reading-view code[class*="language-"] {
    overflow-x: scroll;
    white-space: pre;
    padding: 15px 0px;
}
```
