### ISSUE TITLE
Bug: when multiple color settings defined, each square shows last color before interacted

### ISSUE THREAD

**Issue by KillyMXI** [mgmeyers/obsidian-style-settings#168]
```yaml

    - 
        id: style-settings-bug-note
        title: Note
        description: "Style Settings seems to be bugged. You may not see the actual colors here before interacting with each color picker."
        type: info-text
        markdown: false
    - 
        id: list-threading-active-color-1
        title: Color 1
        type: variable-color
        opacity: false
        format: hsl-values
        default: 'hsl(23, 100%, 45%)'
    - 
        id: list-threading-active-color-2
        title: Color 2
        type: variable-color
        opacity: false
        format: hsl-values
        default: 'hsl(46, 100%, 45%)'
    - 
        id: list-threading-active-color-3
        title: Color 3
        type: variable-color
        opacity: false
        format: hsl-values
        default: 'hsl(70, 100%, 45%)'
    - 
        id: list-threading-active-color-4
        title: Color 4
        type: variable-color
        opacity: false
        format: hsl-values
        default: 'hsl(105, 100%, 45%)'
    - 
        id: list-threading-active-color-5
        title: Color 5
        type: variable-color
        opacity: false
        format: hsl-values
        default: 'hsl(187, 100%, 45%)'
```

Observed after full reset:

![image](https://github.com/user-attachments/assets/bedf3e7f-1fdb-4798-9a1f-3c96dbb7eea5)

Expected (can be seen after resetting individually or opening each color picker):

![image](https://github.com/user-attachments/assets/84ddb65a-0d6e-4ba2-865a-465a75bf3ddb)

- Style Settings version: 1.0.8
- Obsidian version: 1.6.7
