### ISSUE TITLE
Readme example vs. setting up line width

### ISSUE THREAD

**Issue by b1uegh0st** [mgmeyers/obsidian-style-settings#23]
Hi, 
 
 Thanks for the great plug-in. I found the example in your readme about the line-width, was looking for something like that. However, I am not seeing it working (maybe coz I use a theme?). 

**Need**

- If the readme is wrong, hope there can be a fix.
- Else, if it is right, can you show some pointers on how to write a setting to adjust the max-width (possibly a different setting) as in the details I added under here?

I know it is a bit more than an Issue request, but because this was in the Readme so I feel _somewhat_ justified to post this issue. Really want to use your plugin as it solves my exact pain point, just that I don't know how to make it to work in my usecase. 

Thanks,
NA

**Details**
To be exact:
 ```
/* @settings
name: Your Section Name Here
id: a-unique-id
settings:
 - 
 id: line-width
 title: Line width
 description: The maximum line width in rem units
 type: variable-number
 default: 42
 format: rem
*/
```

My other solution, a CSS snippets: (work in all theme, with the `Readable line` settings on).
```
.markdown-preview-view.is-readable-line-width .markdown-preview-sizer, .markdown-source-view.is-readable-line-width .CodeMirror 
{ max-width:42rem; }
```
