### ISSUE TITLE
[Question] Unclear how class-select works, any real-life examples?

### ISSUE THREAD

**Issue by metruzanca** [mgmeyers/obsidian-style-settings#40]
Can I get an example of how this is meant to be used?

From the readme
> class-select creates a dropdown of predefined options for a CSS variable. The id of the setting will be used as the variable name.

With the example given using these as options
```yaml
id: theme-variant
# ...
options:
    - my-class
    - my-other-class
    - and-yet-another
```

It seems as if `class-select` is meant to be a dropdown that lets you pick a class for a css variable, but AFAIK you can't do anything with a classname(so text) set to a css variable. Stuff like `blockquote[class=var(--theme-variant)]` doesn't work, so I'm confused of how we're supposed to use this option.

Being able to pick a class(which then sets stuff via css) for an element sounds cool, but I'm idk how its supposed to work.
