### ISSUE TITLE
Feature Request: Option to toggle a class-toggle via command

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-style-settings#47]
I great feature I could imagine is toggling selected `class-toggles` via a command/hotkey. For example, one could add a `add-command` key to the yaml:

```yaml
id: my-css-class
title: My Toggle
description: Adds my-css-class to the body element
type: class-toggle
add-command: true
```

When set to `true`, it will register a command that enables toggling that specific `class-toggle`. This could be very useful for some features like a focus mode, changing readable line length, toggling between two sizes, etc.
