### ISSUE TITLE
FR: Allow adding quotes around the variable of variable-text types

### ISSUE THREAD

**Issue by HEmile** [mgmeyers/obsidian-style-settings#52]
Use case: Supercharged links likes to prepend emojis. I want users to set those from Style Settings. However, this isn't currently possible. When using `variable-text`, and the following snippet:

```css
.data-link-icon[data-link-category="people"  i]::before {
   content: var(--before);
}
```
then when Style Settings sets the --before variable to "some string", it is added like `content: some string;` But this is not parsed as a string! Instead, I would like it to be `content: 'some string';`. 

This could be achieved by adding an optional `quotes` parameter.
