### ISSUE TITLE
HSL variable-color not working

### ISSUE THREAD

**Issue by megclaypool** [mgmeyers/obsidian-style-settings#57]
Hi there,

I'm super excited about integrating my checkbox snippet with Style Settings! However, I've run into a snag... (I have to admit that it's quite possible the error is on my part!)

Here's the code I've put at the top of my snippet:

```css
/* @settings
name: Meg's Sanctum Checkboxes
id: megs-checkboxes
settings:
    -
        title: Text Color 1
        description: Set the foreground/text color
        id: checkbox-idea-text-color1
        type: variable-color
        format: hex
        default: '#007AFF'
    -
        title: Text Color 2
        description: Set the foreground/text color
        id: checkbox-idea-text-color2
        type: variable-color
        format: hsl
        default: 'hsl(48, 100%, 50%)'
    -
        title: Text Color 3
        description: Set the foreground/text color
        id: checkbox-idea-text-color3
        type: variable-color
        format: rgb
        default: 'rgb(255, 204, 0)'
        alt-format:
            -
                id: checkbox-idea-text-color-hsl
                format: hsl
    -
        title: Text Color 4
        description: Set the foreground/text color
        id: checkbox-idea-text-color4
        type: variable-color
        format: hsl
        opacity: true
        default: 'hsla(48, 100%, 50%, 1)'
*/

:root {
  --megs-red: hsl(350.5, 79.1%, 62.5%);
  --megs-yellow: hsla(62, 100%, 56%, 1);
  --megs-orange: hsla(39, 100%, 61%, 1);
  --megs-green: hsla(169, 71%, 38%, 1);
  --megs-blue: hsla(211, 100%, 50%, 1);
  --megs-purple: hsla(259, 100%, 50%, 1);

  --megs-default-text: hsl(24, 4.4%, 7.8%);

  --checkbox-idea-text-color1: var(--megs-default-text);
  --checkbox-idea-text-color2: var(--megs-default-text);
  --checkbox-idea-text-color3: var(--megs-default-text);
  --checkbox-idea-text-color4: var(--megs-default-text);
}
```
As you can see, I should have 3 color settings. However, when I open style settings I only see two of them; the HSL color isn't appearing. 

![ScreenShot](https://user-images.githubusercontent.com/22053927/152659709-75f3acfc-9dd4-4533-95b8-e38f6a0a5641.png)

Am I setting up "Text Color 2" and "Text Color 4" incorrectly?
