### ISSUE TITLE
QoL Feature Request: Allow Sections to have `collapse: false`

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-style-settings#59]
It's a minor Quality-of-Life thing, but I think most ppl only have one section (the Style Settings from their theme) and having to unfold the section name all the time is a minor annoyance, which is also somewhat unecessary if one has only one section. Basically, allow for this:

```yaml
/* @settings

name: Your Section Name Here
id: a-unique-id
collapsed: false # <- this
settings:
    - 
        id: this-is-a-heading
        title: My Heading
        type: heading
        level: 2
        collapsed: true

*/
```

Alternative, you could even make it the default to always make a section uncollapse if it's a user only has one setting. 🙏
