### ISSUE TITLE
Error when using `variable-select` to change colors

### ISSUE THREAD

**Issue by ceciliamay** [mgmeyers/obsidian-style-settings#62]
Hello there!

I am trying to set up some options to allow the user to choose from a preset of colors for multicolored highlights. 
![image](https://user-images.githubusercontent.com/90643719/159146597-307b62bc-834e-413e-aa3f-6c71f9111581.png)
in code it looks like this:
```
    -
        id: highlight
        title: ⚡ Highlight
        type: heading
        level: 2
        collapsed: true
    -
        id: md-color-highlight-bg
        title: Highlight-only Background Color
        type: variable-select
        default: 'var(color-highlight-yellow)'
        options:
            -
                label: Red
                value: 'var(color-highlight-red)'
            -
                label: Orange
                value: 'var(color-highlight-orange)'
            -
                label: Yellow
                value: 'var(color-highlight-yellow)'
            -
                label: Green
                value: 'var(color-highlight-green)'
            -
                label: Blue
                value: 'var(color-highlight-blue)'
            -
                label: Violet
                value: 'var(color-highlight-violet)'
    -
        id: md-color-bold-highlight-bg
        title: Bold and Highlight Background Color
        type: variable-select
        default: 'var(color-highlight-yellow)'
        options:
            -
                label: Red
                value: 'var(color-highlight-red)'
            -
                label: Orange
                value: 'var(color-highlight-orange)'
            -
                label: Yellow
                value: 'var(color-highlight-yellow)'
            -
                label: Green
                value: 'var(color-highlight-green)'
            -
                label: Blue
                value: 'var(color-highlight-blue)'
            -
                label: Violet
                value: 'var(color-highlight-violet)'
    -
        id: md-color-bold-highlight-bg
        title: Italic and Highlight Background Color
        type: variable-select
        default: 'var(color-highlight-yellow)'
        options:
            -
                label: Red
                value: 'var(color-highlight-red)'
            -
                label: Orange
                value: 'var(color-highlight-orange)'
            -
                label: Yellow
                value: 'var(color-highlight-yellow)'
            -
                label: Green
                value: 'var(color-highlight-green)'
            -
                label: Blue
                value: 'var(color-highlight-blue)'
            -
                label: Violet
                value: 'var(color-highlight-violet)'
    -
        id: md-color-bi-highlight-bg
        title: Bold, Italic and Highlight Background Color
        type: variable-select
        default: 'var(color-highlight-yellow)'
        options:
            -
                label: Red
                value: 'var(color-highlight-red)'
            -
                label: Orange
                value: 'var(color-highlight-orange)'
            -
                label: Yellow
                value: 'var(color-highlight-yellow)'
            -
                label: Green
                value: 'var(color-highlight-green)'
            -
                label: Blue
                value: 'var(color-highlight-blue)'
            -
                label: Violet
                value: 'var(color-highlight-violet)'
    -
        id: custom-highlight
        title: Custom Highlight
        type: heading
        level: 3
        collapsed: true
    -
    // code using variable-themed-color
```

I am trying to use `variable-select` to do this because I want users to have the option to select from presets (through color palettes) while also having the freedom to choose any color they want (through `variable-themed-color` ):
```
--md-color-highlight-bg: var(--color-highlight-yellow); /* for user's custom input */
--color-highlight-yellow: rgba(255, 187, 0, 0.2); /* for color palette */
```

Unfortunately I am getting this error:
![image](https://user-images.githubusercontent.com/90643719/159146978-402cc972-5e37-4665-858e-cf1f074db36e.png)

I am not sure why I am getting this error but I am hoping this is a bug because allowing users to select from preset variables would be very helpful! Setting up classes just to change variables is a lot of (I believe) unneccessary code (this is the only workaround I am aware of so far) 🙏
