### ISSUE TITLE
Restore Default buttons do not restore default

### ISSUE THREAD

**Issue by tonydiep** [mgmeyers/obsidian-style-settings#63]
Clicking "restore default" buttons have no effect

**Comment by midvok** [comment]
I have the same issue.

Only this works for me to apply the default value: First I have to enter a different value manually and hit enter. And only then I can enter the default value and hit enter.

The default button doesn't work. Re-typing the default value manually doesn't work either.

Tested with Obsidian 1.0.3 and `variable-number` to customize font sizes in px.
```
  -
    id: font-ui-small
    title: UI small font size
    description: Used for sidebars and tabs
    type: variable-number
    default: 15
    format: px
```

**Comment by midvok** [comment]
I think I've found a way how to make the default value working. You need to set the same default value also in the `body` element, because when you hit the Default button, no value is actually injected by the Style extension.

So, the following snippet works perfectly for me to set `--font-ui-small` with the default value `15px`.

```css
/* @settings
name: Obsidian Default Theme
id: obsidian-default-theme
settings:
  -
    id: heading-fonts
    title: Fonts
    type: heading
    level: 1
    collapsed: false
  -
    id: font-ui-small
    title: UI small font size
    description: Used for sidebars and tabs
    type: variable-number
    default: 15
    format: px
*/

body {
  --font-ui-small: 15px;
}
```
